2024-10-18 08:32:44.918 -05 [6412] LOG:  empezando checkpoint: time
2024-10-18 08:32:45.421 -05 [6412] LOG:  checkpoint completo: escritos 5 búfers (0.0%); 0 archivos WAL añadidos, 0 eliminados, 0 reciclados; write=0.450 s, sync=0.023 s, total=0.503 s; archivos sincronizados=5, más largo=0.018 s, promedio=0.005 s; distancia=2 kB, estimación=4092 kB; lsn=0/1A24D88, lsn de redo=0/1A24D30
2024-10-18 08:33:06.157 -05 [8884] FATAL:  la autentificación password falló para el usuario «alejo_bdi»
2024-10-18 08:33:06.157 -05 [8884] DETALLE:  La conexión coincidió con el archivo «C:/Program Files/PostgreSQL/17/data/pg_hba.conf» línea 117: «host    all             all             ::1/128                 scram-sha-256»
2024-10-18 11:39:29.553 -05 [16588] LOG:  no se pudo recibir datos del cliente: An existing connection was forcibly closed by the remote host.
	
2024-10-22 19:43:39.354 -05 [10884] ERROR:  no se reconoce la codificaciÃ³n: Â«base32Â»
2024-10-22 19:43:39.354 -05 [10884] CONTEXTO:  sentencia SQL: Â«SELECT encode(set_byte(set_byte(md5(random()::text)::bytea, 0, trunc(random()*256)::int), 1, trunc(random()*256)::int), 'base32')Â»
	funciÃ³n PL/pgSQL ulid_generate() en la lÃ­nea 5 en sentencia SQL
2024-10-22 19:43:39.354 -05 [10884] SENTENCIA:  INSERT INTO empleados (nombre) VALUES ('Alejo Jaimes');
2024-10-22 19:44:52.325 -05 [10884] ERROR:  error de sintaxis al final de la entrada en carÃ¡cter 528
2024-10-22 19:44:52.325 -05 [10884] SENTENCIA:  CREATE OR REPLACE FUNCTION generate_ulid()RETURNS TEXT AS $$DECLARE    ulid TEXT;    timestamp_part TEXT;    randomness_part TEXT;BEGIN    -- Generar la parte del timestamp basado en el tiempo actual en milisegundos    timestamp_part := lpad(to_hex((extract(epoch from clock_timestamp()) * 1000)::bigint), 12, '0');    -- Generar la parte aleatoria del ULID (80 bits)    randomness_part := encode(gen_random_bytes(10), 'hex');    -- Combinar ambas partes    ulid := lower(timestamp_part || randomness_part);    RETURN ulid;END;$$ LANGUAGE plpgsql;
2024-10-22 19:45:35.273 -05 [10884] ERROR:  no existe la funciÃ³n gen_random_bytes(integer) en carÃ¡cter 27
2024-10-22 19:45:35.273 -05 [10884] HINT:  Ninguna funciÃ³n coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversiÃ³n explÃ­cita de tipos.
2024-10-22 19:45:35.273 -05 [10884] CONSULTA:  randomness_part := encode(gen_random_bytes(10), 'hex')
2024-10-22 19:45:35.273 -05 [10884] CONTEXTO:  funciÃ³n PL/pgSQL generate_ulid() en la lÃ­nea 11 en asignaciÃ³n
2024-10-22 19:45:35.273 -05 [10884] SENTENCIA:  SELECT generate_ulid();
2024-10-22 19:47:55.491 -05 [6412] LOG:  empezando checkpoint: time
2024-10-22 19:48:06.475 -05 [6412] LOG:  checkpoint completo: escritos 99 búfers (0.6%); 0 archivos WAL añadidos, 0 eliminados, 0 reciclados; write=10.912 s, sync=0.055 s, total=10.986 s; archivos sincronizados=53, más largo=0.009 s, promedio=0.002 s; distancia=451 kB, estimación=3728 kB; lsn=0/1A95BE0, lsn de redo=0/1A95B50
2024-10-22 19:48:11.472 -05 [10884] ERROR:  no se reconoce la codificaciÃ³n: Â«base32Â»
2024-10-22 19:48:11.472 -05 [10884] CONTEXTO:  sentencia SQL: Â«SELECT encode(set_byte(set_byte(md5(random()::text)::bytea, 0, trunc(random()*256)::int), 1, trunc(random()*256)::int), 'base32')Â»
	funciÃ³n PL/pgSQL ulid_generate() en la lÃ­nea 5 en sentencia SQL
2024-10-22 19:48:11.472 -05 [10884] SENTENCIA:  INSERT INTO empleados (nombre) VALUES ('Alejo Jaimes');
2024-10-22 19:52:55.471 -05 [6412] LOG:  empezando checkpoint: time
2024-10-22 19:52:56.052 -05 [6412] LOG:  checkpoint completo: escritos 6 búfers (0.0%); 0 archivos WAL añadidos, 0 eliminados, 0 reciclados; write=0.543 s, sync=0.008 s, total=0.582 s; archivos sincronizados=5, más largo=0.003 s, promedio=0.002 s; distancia=1 kB, estimación=3356 kB; lsn=0/1A962B8, lsn de redo=0/1A96260
2024-10-23 14:22:10.193 -05 [19468] ERROR:  no existe la relaciÃ³n Â«estudiantesÂ» en carÃ¡cter 15
2024-10-23 14:22:10.193 -05 [19468] SENTENCIA:  select * from estudiantes;
